name: go
on: [push]
jobs:

    test:
        runs-on: ubuntu-latest
        steps:

            - name: Set up Go 1.13
              uses: actions/setup-go@v1
              with:
                  go-version: 1.13
              id: go

            - name: Check out code into the Go module directory
              uses: actions/checkout@v1

            - name: Caching modules
              uses: actions/cache@v1
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-aw-${{ hashFiles('**/go.sum') }}

            - name: Get dependencies
              run: |
                  export PATH=$PATH:$(go env GOPATH)/bin
                  go get -u github.com/onsi/ginkgo/ginkgo
                  go get -u github.com/onsi/gomega/...
                  go get -u golang.org/x/lint/golint
                  go get -u github.com/loongy/covermerge
                  go get -u github.com/mattn/goveralls

            - name: Run vetting
              run: |
                cd $GITHUB_WORKSPACE
                export PATH=$PATH:$(go env GOPATH)/bin
                go vet ./...

            - name: Run linting
              run: |
                cd $GITHUB_WORKSPACE
                export PATH=$PATH:$(go env GOPATH)/bin
                go get -u golang.org/x/lint/golint
                golint ./...

            - name: Run tests and report test coverage
              env:
                  COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  export PATH=$PATH:$(go env GOPATH)/bin
                  export MESSAGE_HISTORY=false
                  export REPLAY_MODE=false
                  cd $GITHUB_WORKSPACE
                  CI=true ginkgo --v --race --cover --coverprofile coverprofile.out ./...
                  covermerge                   \
                    scheduler/coverprofile.out \
                    timer/coverprofile.out     \
                    mq/coverprofile.out        \
                    process/coverprofile.out   \
                    replica/coverprofile.out   \
                    coverprofile.out > coverprofile.out
                  goveralls -coverprofile=coverprofile.out -service=github
